### ISSUE TITLE
dictionary.csv to DICTIONARY.md markdown formatting changes

### ISSUE THREAD

**Issue by CooperStansbury** [Display-Lab/fio#139]
@grosscol 
When I reformatted our terms in FIO the `DICTIONARY.md` markdown changed with it (or I made a stupid mistake somewhere)... I'm not smart enough to figure out this line of `make-dict.sh` to fix the formatting, but it looks like a comma is throwing things off:

Line 41:
`tail -n +2 ${CSV_FILE} | sort | sed -e 's|^\([^,]*\),\([^,]*\),\(.*\)|## \1\n### \2\n\3\n|' > ${MD_FILE}`

Would you be kind enough to point me to a place to learn how to work with this and I can make the change?

Thanks,

**Comment by CooperStansbury** [comment]
I added a very kludgy fix to my branch with example formatting. Just add a literal newline for `sed` as shown below:

Line 41:
`tail -n +2 ${CSV_FILE} | sort | sed -e 's|^\([^,]*\),\([^,]*\),\(.*\)|## \1\
### \3\2\n|' > ${MD_FILE}`

Works (at least on my machine). There's example formatting in `DICTIONARY.md` that looks a little cleaner, in my opinion.

**Comment by CooperStansbury** [comment]
Sorry, forgot that issues are markdown...

```
tail -n +2 ${CSV_FILE} | sort | sed -e 's|^\([^,]*\),\([^,]*\),\(.*\)|## \1\
### \3\2\n|' > ${MD_FILE}
```

**Comment by grosscol** [comment]
I'm not entirely sure what's going on here?  I think I'm missing the context you're in.  Am I correct in assuming the following:  You're working on a branch, some changes were made to fio-edit.owl, and those have subsequently altered the output of `make-dict.sh`?

If that's the case, make a PR from the branch you're working from.  Maybe prefix the PR title with [WIP] so that we know it's a work in progress.

That way, we can see and directly comment on the code.

**Comment by CooperStansbury** [comment]
Submitted [PR](https://github.com/Display-Lab/fio/pull/140)
