### ISSUE TITLE
Term: Behavior Change Intervention

### ISSUE THREAD

**Issue by john-rincon** [Display-Lab/fio#37]
*Term name - Intervention
*Definition - An action that is taken to increase a performer's awareness of his/her performance data
*Comment (rdfs:comment)
*Reference - none
*Example Usage (IAO_0000112) - n/a, new term
*Example:

**Comment by zachll** [comment]
*Term name - Behavior Change Intervention
*Definition - An activity, product or service that may be used by an individual, organisation or social grouping to change the behaviour of a person, group, organisation or population from what would have occurred otherwise.
*Comment (rdfs:comment)
*Reference - West, R., Michie, S.: A Guide to Development and Evaluation of Digital Behaviour Change Interventions in Healthcare. Silverback Publishing
*Example Usage (IAO_0000112) - n/a, new term
*Example:

**Comment by zachll** [comment]
@john-rincon
