### ISSUE TITLE
Term: performer

### ISSUE THREAD

**Issue by john-rincon** [Display-Lab/fio#7]
*Term name- Performer
*Definition - is an entity to which observed or expected performance information can be attributed, including healthcare professionals, teams and organizations that are the recipients of a report, as well as benchmarks, standards, and goals that are applied as performance comparators.
*Comment (rdfs:comment)- still need
*Reference- L3 working paper
*Example Usage- n/a, new term

**Comment by john-rincon** [comment]
Added to ontology

**Comment by zachll** [comment]
Proposed revision for this definition:

*Term name- performer
*Definition - is a dimension in a relational information display whose elements contain performance information
*Comment (rdfs:comment)-
*Reference-
*Example Usage-

**Comment by CooperStansbury** [comment]
Based on a teem conversation we need to consider the implications of 'performer' also referring to the human performer and not just the dimension of a RID. Many of the other term definitions depend on performer being defined as a human engaged in a measured activity, and not the RID centric definition. Food for thought.

**Comment by zachll** [comment]
Good point. It seems like an essential distinction to make in order to know if we are referring to a dimension in a display, or the entity that it represents. We will likely experience confusion unless we revise any other dependent definitions that do not keep that distinction clear. An option we have would be to use the term performer to refer to the represented dimension, and "performer dimension" to refer to the representing dimension. We could follow suit for time, data, measure, and other dimensions we identify.
