### ISSUE TITLE
Term: Time (1) display

### ISSUE THREAD

**Issue by leedahee** [Display-Lab/fio#93]
Definition: A time(1) display is a performance summary display that represents one time point.

**Comment by john-rincon** [comment]
@leedahee @zachll  , this doesn't seem to follow the taxonomy, as this is a Aristotelian branch from performance summary display, rather than single or multi-performer display. To be consistent with the diagram, I think there should be two of these terms, one which branches from single performer, and one which branches from mutli. This also would apply to #87

**Comment by john-rincon** [comment]
I'll add it as is for now, but won't push to master until this issue is closed
